// Modules to include in the tree.
units[] =
{
	//"Ares_Module_Test",
	"Ares_Module_Arsenal_Create_Nato",
	"Ares_Module_RemoveNvgGroup",
	"Ares_Module_ForceLightsOn",
	"Ares_Module_ForceLightsOff",
	"Ares_Module_ForceLightsAuto",
	"Ares_Module_SurrenderSingleUnit",
	"Ares_Module_Teleport_All",
	"Ares_Module_Teleport_Single",
	"Ares_Module_Teleport_Zeus",
	"Ares_Module_Teleport_Side_Nato",
	"Ares_Module_Teleport_Side_Independent",
	"Ares_Module_Teleport_Side_Csat",
	"Ares_Module_Teleport_Side_Civilian",
	"Ares_Module_Teleport_CreateTeleporter",
	"Ares_Module_Save_Objects_For_Composition",
	"Ares_Module_Save_Objects_For_Paste",
	"Ares_Module_Paste_Objects",
	"Ares_Module_Garrison_Nearest",
	"Ares_Module_UnGarrison",
	"Ares_Module_Search_Nearby_Building",
	"Ares_Module_Disable_Thermals",
	"Ares_Module_Enable_Thermals",
};
